### ISSUE TITLE
SPELL_CHECKERS deprecated message

### ISSUE THREAD

**Issue by bumpux** [ivoanjo/s3_website_revived#1]
Love that s3_website has new home! Many thanks.

s3_website 4.0.0 has been giving me this deprecation message. 

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

**Comment by ivoanjo** [comment]
Thanks for the report! I've just released 4.0.1 with a fix for this. Furthermore, I've added a version prompt as well:

```
$ bundle exec s3_website --version
s3_website_revived 4.0.1
```
