### ISSUE TITLE
Public access now blocked by default for new S3 buckets

### ISSUE THREAD

**Issue by guillerodriguez** [ivoanjo/s3_website_revived#2]
Starting April 2023, Amazon has changed the default configuration for new S3 buckets and now "S3 Block Public Access" is enabled by default: https://aws.amazon.com/es/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

For new S3 buckets that will be used to host a website, it is necessary to modify this setting.

Configuration of the S3 bucket is actually handled by the [configure-s3-website](https://github.com/laurilehmijoki/configure-s3-website) gem. I [opened an issue](https://github.com/laurilehmijoki/configure-s3-website/issues/26) in the upstream repo, but the author informed me that the gem is no longer maintained.

So in order to fix this I understand that you would first need to fork configure-s3-website and modify s3_website_revived's [gemspec file](https://github.com/ivoanjo/s3_website_revived/blob/master/s3_website.gemspec) to use the forked gem. Then the forked gem can be patched to fix the issue.

Do you agree with this?

If so, I can help preparing a PR once the configure-s3-website gem is forked.

Please let me know if this sounds ok to you.

**Comment by ivoanjo** [comment]
:wave: nice to meet you Guillermo!

To be honest, I never used the `configure-s3-website` bits -- I did my own setup and then used s3website just for the uploady bits, so I'm not sure I'm the best warden for it :)

Can I convince you to fork it yourself, and I'll link to your version of the gem from `s3_website_revived`? :wink: 

If not, that's fine, and I'm still up for going with your initial suggestion.

**Comment by guillerodriguez** [comment]
Yes, sure! I will get back to you.

**Comment by guillerodriguez** [comment]
Sorry for the delay, here's an updated gem that fixes the mentioned issue: https://rubygems.org/gems/configure-s3-website-ng

Sources: https://github.com/ingelabs/configure-s3-website

**Comment by ivoanjo** [comment]
Awesome! I'm a bit busy over the next few days, but I'll update the dependency as soon as things calm down a bit :)

**Comment by ivoanjo** [comment]
@guillerodriguez Thanks a lot! I finally had a bit of time today, and I've:

1. Adopted your new gem as a dependency
2. Put out a new release (4.0.2) using it
3. Sent you an invite to collaborate on this repo, since like me you seem to be interested in helping keep this tiny useful gem alive :)

**Comment by guillerodriguez** [comment]
Great! Thank you ☺️
